from matplotlib.pylab import rand
from sage.all import VectorSpace, Matrix, GF, ZZ, randint, PolynomialRing, randint, shuffle
import scipy as sp
from richelot_rm.genus_two_structures import GenusTwoJacobianStructure
from richelot_rm.richelot_jacobian_isogeny import *
from itertools import product

def get_2_symplectic_basis(g2_structure: GenusTwoJacobianStructure):
    J = g2_structure.jac
    Rx = g2_structure.Rx
    x = g2_structure.x
    h = g2_structure.h
    roots = h.roots(multiplicities=False)
    assert len(roots) == 6
    shuffle(roots)

    T1x = (x - roots[0]) * (x - roots[1])
    T3x = (x - roots[0]) * (x - roots[2])  # must share a factor with T1, none others
    T2x = (x - roots[3]) * (x - roots[4])  # must share a factor with T4, none others
    T4x = (x - roots[3]) * (x - roots[5])  # must share a factor with T2, none others

    T1 = JacobianPoint(J([Rx(T1x), Rx(0)]))
    T2 = JacobianPoint(J([Rx(T2x), Rx(0)]))
    T3 = JacobianPoint(J([Rx(T3x), Rx(0)]))
    T4 = JacobianPoint(J([Rx(T4x), Rx(0)]))

    return [T1, T2, T3, T4]


def get_all_2_kernels(
    g2_structure: GenusTwoJacobianStructure, randomize_generators=False
):
    symplectic_basis = get_2_symplectic_basis(g2_structure)
    V = VectorSpace(GF(2), 4)
    B = Matrix(GF(2), [[0, 0, 1, 0], [0, 0, 0, 1], [-1, 0, 0, 0], [0, -1, 0, 0]])
    subspaces = []
    for W in V.subspaces(2):
        gens = W.gens()
        u, v = gens[0], gens[1]
        if (u * B) * v == 0:
            subspaces.append(Matrix([u, v]))

    def vec_to_point(vec):
        components = [ZZ(vec[i]) * symplectic_basis[i] for i in range(4)]
        return components[0] + components[1] + components[2] + components[3]

    maximal_isotropic_subgroups = []
    for u, v in subspaces:
        gen1 = vec_to_point(u)
        gen2 = vec_to_point(v)
        if randomize_generators:
            if bool(randint(0, 1)):
                if bool(randint(0, 1)):
                    gen1 = gen1 + gen2
                else:
                    gen2 = gen1 + gen2
        kernel = (gen1, gen2)
        maximal_isotropic_subgroups.append(kernel)

    return maximal_isotropic_subgroups

def test_splitting_detection():
    p = 2**11 * 3 - 1
    Fp2 = GF(p**2)
    z2 = Fp2.gen()
    Rx = PolynomialRing(Fp2, "x")
    x = Rx.gen()
    h = x**6 + 1
    # since 6 | p^2 - 1, this polynomial splits completely and is square free
    g2_structure = GenusTwoJacobianStructure(h)
    kernels = get_all_2_kernels(g2_structure)
    assert len(kernels) == 15
    assert all(
        is_2_kernel_jac(kernel) for kernel in kernels
    )

    split_kernels = [
        kernel for kernel in kernels if is_2_kernel_jac_split(kernel)
    ]
    assert len(split_kernels) == 6, "Incorrect number of split kernels detected: {}".format(len(split_kernels))

def test_split_isogeny_example():
    # This line was generated by the test product file:
    # 636*z2 + 3958, 486*z2 + 4663 -> x^6 + (5191*z2 + 5626)*x^4 + (2839*z2 + 5640)*x^2 + 4795*z2 + 1488
    p = 2**11 * 3 - 1
    Fp2 = GF(p**2)
    z2 = Fp2.gen()
    Rx = PolynomialRing(Fp2, "x")
    x = Rx.gen()
    h = x**6 + (5191 * z2 + 5626) * x**4 + (2839 * z2 + 5640) * x**2 + 4795 * z2 + 1488
    g2_structure = GenusTwoJacobianStructure(h)

    kernels = get_all_2_kernels(g2_structure)
    assert len(kernels) == 15

    assert all(
        is_2_kernel_jac(kernel) for kernel in kernels
    ), "Not all kernels are valid 2-isogeny kernels."

    split_kernels = [
        kernel for kernel in kernels if is_2_kernel_jac_split(kernel)
    ]
    assert len(split_kernels) == 1
    split_kernel = split_kernels[0]

    codomain, isogeny = jacobian_to_product_2_isogeny(split_kernel)
    assert codomain[0].j_invariant() == 636 * z2 + 3958
    assert codomain[1].j_invariant() == 486 * z2 + 4663
    assert isogeny(split_kernel[0]) == 0
    assert isogeny(split_kernel[1]) == 0
    Ts_img = [isogeny(T) for T in get_2_symplectic_basis(g2_structure)]
    Ts_img_set = set()
    for pt in Ts_img:
        for other_pt in Ts_img:
            sum_pt = pt + other_pt
            Ts_img_set.add(sum_pt)

    assert len(Ts_img_set) == 4, "Image of 2-torsion does not have size 4."


if __name__ == "__main__":
    test_split_isogeny_example
    test_splitting_detection()
