
from sage.all import (
    VectorSpace,
    Matrix,
    GF,
    ZZ,
    randint,
    PolynomialRing,
    randint,
)
import scipy as sp
from richelot_rm.genus_two_structures import GenusTwoJacobianStructure
from richelot_rm.richelot_jacobian_isogeny import *


def get_all_2_kernels(
    g2_structure: GenusTwoJacobianStructure, randomize_generators=False
):
    symplectic_basis = get_symplectic_two_torsion_jac(g2_structure)
    V = VectorSpace(GF(2), 4)
    B = Matrix(GF(2), [[0, 0, 1, 0], [0, 0, 0, 1], [-1, 0, 0, 0], [0, -1, 0, 0]])
    subspaces = []
    for W in V.subspaces(2):
        gens = W.gens()
        u, v = gens[0], gens[1]
        if (u * B) * v == 0:
            subspaces.append(Matrix([u, v]))

    def vec_to_point(vec):
        components = [ZZ(vec[i]) * symplectic_basis[i] for i in range(4)]
        return components[0] + components[1] + components[2] + components[3]

    maximal_isotropic_subgroups = []
    for u, v in subspaces:
        gen1 = vec_to_point(u)
        gen2 = vec_to_point(v)
        if randomize_generators:
            if bool(randint(0, 1)):
                if bool(randint(0, 1)):
                    gen1 = gen1 + gen2
                else:
                    gen2 = gen1 + gen2
        kernel = (gen1, gen2)
        maximal_isotropic_subgroups.append(kernel)

    return maximal_isotropic_subgroups


def test_split_isogeny_example():
    # This line was generated by the test product file:
    # 636*z2 + 3958, 486*z2 + 4663 -> x^6 + (5191*z2 + 5626)*x^4 + (2839*z2 + 5640)*x^2 + 4795*z2 + 1488
    p = 2**11 * 3 - 1
    Fp2 = GF(p**2)
    z2 = Fp2.gen()
    Rx = PolynomialRing(Fp2, "x")
    x = Rx.gen()
    h = x**6 + (5191 * z2 + 5626) * x**4 + (2839 * z2 + 5640) * x**2 + 4795 * z2 + 1488
    g2_structure = GenusTwoJacobianStructure(h)

    kernels = get_all_2_kernels(g2_structure)
    assert len(kernels) == 15

    assert all(
        is_2_kernel_jac(kernel) for kernel in kernels
    ), "Not all kernels are valid 2-isogeny kernels."

    for kernel in kernels:
        kernel_set = [2 * kernel[0], kernel[0], kernel[1], kernel[0] + kernel[1]]
        kernel_set = set(kernel_set)
        assert (
            len(kernel_set) == 4
        ), f"Kernel does not have size 4: {kernel_set}, kernel: {kernel}"

    split_kernels = [kernel for kernel in kernels if is_2_kernel_jac_split(kernel)]
    assert len(split_kernels) == 1
    split_kernel = split_kernels[0]

    codomain, isogeny = jacobian_to_product_2_isogeny(split_kernel)
    assert codomain[0].j_invariant() == 636 * z2 + 3958
    assert codomain[1].j_invariant() == 486 * z2 + 4663
    assert isogeny(split_kernel[0]) == 0
    assert isogeny(split_kernel[1]) == 0

    Ts_img = [isogeny(T) for T in get_symplectic_two_torsion_jac(g2_structure)]
    Ts_img += [ProductPoint(codomain[0](0), codomain[1](0))]

    Ts_img_set = set()
    for pt in Ts_img:
        for other_pt in Ts_img:
            sum_pt = pt + other_pt
            Ts_img_set.add(sum_pt)

    assert len(Ts_img_set) == 4, f"Image of 2-torsion does not have size 4 {Ts_img_set}"

def test_type_6():
    p = 2**11 * 3 - 1
    Fp2 = GF(p**2)
    z2 = Fp2.gen()
    Rx = PolynomialRing(Fp2, "x")
    x = Rx.gen()
    h = x**5 + x
    assert 4 | p**2 - 1
    # since 4 | p^2 - 1, this polynomial splits completely and is square free
    g2_structure = GenusTwoJacobianStructure(h)
    kernels = get_all_2_kernels(g2_structure)
    assert len(kernels) == 15
    assert all(is_2_kernel_jac(kernel) for kernel in kernels)

    split_kernels = [kernel for kernel in kernels if is_2_kernel_jac_split(kernel)]
    non_split_kernels = [
        kernel for kernel in kernels if not is_2_kernel_jac_split(kernel)
    ]

    product_codomains = set()
    for kernel in split_kernels:
        codomain, isogeny = jacobian_to_product_2_isogeny(kernel)
        product_codomains.add((codomain[0].j_invariant(), codomain[1].j_invariant()))

    jacobian_codomains = set()
    for kernel in non_split_kernels:
        codomain, isogeny = jacobian_to_jacobian_2_isogeny(kernel)
        jacobian_codomains.add(codomain.get_isomorphism_class_invariants())

    # From Florian and Smith
    assert len(split_kernels) == 6
    assert len(product_codomains) == 1
    assert len(jacobian_codomains) == 3
    assert g2_structure.get_isomorphism_class_invariants() in jacobian_codomains


def test_type_5():
    p = 2**11 * 3 - 1
    Fp2 = GF(p**2)
    z2 = Fp2.gen()
    Rx = PolynomialRing(Fp2, "x")
    x = Rx.gen()
    h = x**6 + 1
    assert 6 | p**2 - 1
    # since 6 | p^2 - 1, this polynomial splits completely and is square free
    g2_structure = GenusTwoJacobianStructure(h)
    kernels = get_all_2_kernels(g2_structure)
    assert len(kernels) == 15
    assert all(is_2_kernel_jac(kernel) for kernel in kernels)

    split_kernels = [kernel for kernel in kernels if is_2_kernel_jac_split(kernel)]
    non_split_kernels = [
        kernel for kernel in kernels if not is_2_kernel_jac_split(kernel)
    ]

    product_codomains = set()
    for kernel in split_kernels:
        codomain, isogeny = jacobian_to_product_2_isogeny(kernel)
        product_codomains.add((codomain[0].j_invariant(), codomain[1].j_invariant()))

    jacobian_codomains = set()
    for kernel in non_split_kernels:
        codomain, isogeny = jacobian_to_jacobian_2_isogeny(kernel)
        jacobian_codomains.add(codomain.get_isomorphism_class_invariants())

    # From Florian and Smith
    assert len(split_kernels) == 4
    assert len(product_codomains) == 2
    assert (0, 0) in product_codomains
    assert len(jacobian_codomains) == 3
    assert g2_structure.get_isomorphism_class_invariants() in jacobian_codomains


def test_type_4():
    p = 2**11 * 3 - 1
    Fp2 = GF(p**2)
    assert 3 | p**2 - 1
    zeta_3 = Fp2.multiplicative_generator() ** ((p**2 - 1) // 3)
    Rx = PolynomialRing(Fp2, "x")
    x = Rx.gen()
    u = Fp2.random_element()
    sv = (u + 1) * (u - zeta_3) / ((u - 1) * (u + zeta_3))
    tv = (u + 1) * (u - zeta_3**2) / ((u - 1) * (u + zeta_3**2))
    h = (x**2 - 1) * (x**2 - sv**2) * (x**2 - tv**2)
    g2_structure = GenusTwoJacobianStructure(h)
    kernels = get_all_2_kernels(g2_structure)
    assert len(kernels) == 15
    assert all(is_2_kernel_jac(kernel) for kernel in kernels)

    split_kernels = [kernel for kernel in kernels if is_2_kernel_jac_split(kernel)]
    non_split_kernels = [
        kernel for kernel in kernels if not is_2_kernel_jac_split(kernel)
    ]

    product_codomains = set()
    for kernel in split_kernels:
        codomain, isogeny = jacobian_to_product_2_isogeny(kernel)
        product_codomains.add((codomain[0].j_invariant(), codomain[1].j_invariant()))

    jacobian_codomains = set()
    for kernel in non_split_kernels:
        codomain, isogeny = jacobian_to_jacobian_2_isogeny(kernel)
        jacobian_codomains.add(codomain.get_isomorphism_class_invariants())

    # From Florian and Smith
    assert len(split_kernels) == 3
    assert len(product_codomains) == 1 or len(product_codomains) == 2 or len(product_codomains) == 3
    assert len(jacobian_codomains) == 6


def test_type_3():
    p = 2**11 * 3 - 1
    Fp2 = GF(p**2)
    z2 = Fp2.gen()
    Rx = PolynomialRing(Fp2, "x")
    x = Rx.gen()
    u = Fp2.random_element()
    h = (x**2 - 1) * (x**2 - u**2) * (x**2 - (1 / u**2))
    g2_structure = GenusTwoJacobianStructure(h)
    kernels = get_all_2_kernels(g2_structure)
    assert len(kernels) == 15
    assert all(is_2_kernel_jac(kernel) for kernel in kernels)

    split_kernels = [kernel for kernel in kernels if is_2_kernel_jac_split(kernel)]
    non_split_kernels = [
        kernel for kernel in kernels if not is_2_kernel_jac_split(kernel)
    ]

    product_codomains = set()
    for kernel in split_kernels:
        codomain, isogeny = jacobian_to_product_2_isogeny(kernel)
        product_codomains.add((codomain[0].j_invariant(), codomain[1].j_invariant()))

    jacobian_codomains = set()
    for kernel in non_split_kernels:
        codomain, isogeny = jacobian_to_jacobian_2_isogeny(kernel)
        jacobian_codomains.add(codomain.get_isomorphism_class_invariants())

    # From Florian and Smith
    assert len(split_kernels) == 6 or len(split_kernels) == 2
    assert len(product_codomains) == 2 or len(product_codomains) == 3
    assert len(jacobian_codomains) == 5 or len(jacobian_codomains) == 6
    assert g2_structure.get_isomorphism_class_invariants() in jacobian_codomains

if __name__ == "__main__":
    test_split_isogeny_example()
    test_type_6()
    test_type_5()
    test_type_4()
    test_type_3()
